language: java
jdk:
  - openjdk13

before_install:
  - chmod +x ./mvnw
script: mvn clean install

cache:
  directories:
  - node_modules

after_success:
  - mvn clean test jacoco:report coveralls:report
